"""
This script is generated by AI and is only meant to automate the process of
accumulating data item definitions from the Refinitiv Data Item Browser,
instead of manually inspecting them one by one or copying and pasting from
the browser.
These definitions are used to classify the usefulness of each data item
for the training process.

Fetch Data Item Definitions from Refinitiv Data Item Browser

Automates your local Chrome browser to look up definitions for each
data item code and saves results to a JSON file.

PREREQUISITES:
  1. pip install selenium
  2. Quit Chrome completely, then relaunch with remote debugging:
       /Applications/Google\\ Chrome\\ Beta.app/Contents/MacOS/Google\\ Chrome\\ Beta \\
         --remote-debugging-port=9222 \\
         --user-data-dir="$HOME/chrome-debug-profile"
  3. Log into Refinitiv Workspace and open the Data Item Browser
  4. Run:  python fetch_definitions.py
"""

import json
import time
import sys
from pathlib import Path
from data.constants import data_item_codes

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import (
    TimeoutException,
    StaleElementReferenceException,
    NoSuchElementException,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
CHROME_DEBUG_PORT = 9222
OUTPUT_FILE = Path(__file__).parent / "definitions.json"
PROGRESS_FILE = Path(__file__).parent / "definitions_progress.json"
WAIT_TIMEOUT = 15
PAUSE_BETWEEN = 2
MAX_RETRIES = 3

# ---------------------------------------------------------------------------
# Data item codes
# ---------------------------------------------------------------------------
DATA_ITEM_CODES = data_item_codes.DATA_ITEM_CODES


# ---------------------------------------------------------------------------
# Iframe navigation
# ---------------------------------------------------------------------------

# The Data Item Browser is nested 5 iframes deep:
#   main -> AppFrame -> internal -> AppFrame -> EikonNowMarker -> AppFrame
IFRAME_CHAIN = [
    ("name", "AppFrame"),       # workspace container
    ("name", "internal"),       # contentframe / internal
    ("name", "AppFrame"),       # AppContainer
    ("name", "EikonNowMarker"), # contentframe named EikonNowMarker
    ("name", "AppFrame"),       # actual DIB app
]


def navigate_to_dib_frame(driver):
    """Switch through the iframe chain to reach the Data Item Browser frame."""
    driver.switch_to.default_content()
    for attr, value in IFRAME_CHAIN:
        try:
            WebDriverWait(driver, 10).until(
                EC.frame_to_be_available_and_switch_to_it((By.NAME, value))
            )
        except TimeoutException:
            # Fallback: try by CSS selector for iframes without name
            iframes = driver.find_elements(By.TAG_NAME, "iframe")
            switched = False
            for iframe in iframes:
                if iframe.get_attribute(attr) == value:
                    driver.switch_to.frame(iframe)
                    switched = True
                    break
            if not switched:
                raise RuntimeError(
                    f"Could not find iframe with {attr}={value!r}. "
                    f"Available iframes: {[f.get_attribute('name') for f in iframes]}"
                )


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def load_progress() -> dict:
    if PROGRESS_FILE.exists():
        with open(PROGRESS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_progress(definitions: dict) -> None:
    with open(PROGRESS_FILE, "w", encoding="utf-8") as f:
        json.dump(definitions, f, indent=2, ensure_ascii=False)


def connect_to_chrome() -> webdriver.Chrome:
    options = Options()
    options.add_experimental_option("debuggerAddress", f"127.0.0.1:{CHROME_DEBUG_PORT}")
    return webdriver.Chrome(options=options)


def clear_search_bar(search_input):
    """Clear the search bar reliably using keyboard shortcuts."""
    search_input.click()
    time.sleep(0.2)
    # Select all + delete (Mac)
    search_input.send_keys(Keys.COMMAND + "a")
    time.sleep(0.1)
    search_input.send_keys(Keys.DELETE)
    time.sleep(0.3)
    # Fallback with Ctrl if still has text
    if search_input.get_attribute("value"):
        search_input.send_keys(Keys.CONTROL + "a")
        search_input.send_keys(Keys.DELETE)
        time.sleep(0.2)


def get_current_definition(driver) -> str:
    """Read the current definition text from the span."""
    try:
        span = driver.find_element(
            By.CSS_SELECTOR,
            'span[ng-bind-html="udipDefinitionTabVM.definitionText"]'
        )
        return span.text.strip()
    except (NoSuchElementException, StaleElementReferenceException):
        return ""


def wait_for_definition_change(driver, previous_text: str, timeout: int = WAIT_TIMEOUT) -> str | None:
    """Wait until the definition span text changes from previous_text."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            text = get_current_definition(driver)
            if text and text != previous_text:
                return text
        except Exception:
            pass
        time.sleep(0.3)
    return None


def fetch_definition(driver, code: str) -> str | None:
    """
    Type a data item code into the search bar, wait for the definition
    to auto-load, and extract the text.
    """
    # Snapshot the current definition so we can detect when it changes
    old_definition = get_current_definition(driver)

    # Find the search bar: input[type="search"][placeholder="Find Data Item"]
    search_input = WebDriverWait(driver, WAIT_TIMEOUT).until(
        EC.presence_of_element_located((
            By.CSS_SELECTOR,
            'input[ng-model="model.searchText"]'
        ))
    )

    # Clear and type
    clear_search_bar(search_input)
    search_input.send_keys(code)
    time.sleep(2.0)  # give Angular time to react

    # Wait for definition to change
    new_definition = wait_for_definition_change(driver, old_definition)
    if new_definition:
        return new_definition

    # Fallback: just read whatever is there now
    text = get_current_definition(driver)
    return text if text else None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Refinitiv Data Item Definition Fetcher")
    print("=" * 60)
    print(f"Total codes to look up: {len(DATA_ITEM_CODES)}")

    # Load any previous progress (only count codes with actual definitions)
    definitions = load_progress()
    already_done = {k for k, v in definitions.items() if v is not None}
    remaining = [c for c in DATA_ITEM_CODES if c not in already_done]

    if already_done:
        print(f"Resuming: {len(already_done)} already fetched, {len(remaining)} remaining")
    print()

    # Connect to Chrome
    print(f"Connecting to Chrome (port {CHROME_DEBUG_PORT})...")
    try:
        driver = connect_to_chrome()
    except Exception as e:
        print(f"\nERROR: Could not connect to Chrome.\n{e}")
        sys.exit(1)

    print(f"Connected! Current URL: {driver.current_url}")

    # Navigate into the nested iframe chain to reach the DIB app
    print("Navigating into Data Item Browser iframe...")
    try:
        navigate_to_dib_frame(driver)
    except RuntimeError as e:
        print(f"\nERROR: {e}")
        sys.exit(1)

    # Verify we can see the search bar
    try:
        search = driver.find_element(
            By.CSS_SELECTOR, 'input[ng-model="model.searchText"]'
        )
        print(f"Found search bar (placeholder: {search.get_attribute('placeholder')!r})")
    except NoSuchElementException:
        print("ERROR: Could not find the search bar inside the DIB frame.")
        sys.exit(1)

    # Verify we can see the definition span
    try:
        defn = driver.find_element(
            By.CSS_SELECTOR,
            'span[ng-bind-html="udipDefinitionTabVM.definitionText"]'
        )
        print(f"Found definition span (current text: {defn.text[:60]!r}...)")
    except NoSuchElementException:
        print("WARNING: Definition span not visible yet (may appear after first search)")

    print()

    # Process each code
    failed = {}
    for i, code in enumerate(remaining, 1):
        pct = ((len(already_done) + i) / len(DATA_ITEM_CODES)) * 100
        print(
            f"[{len(already_done)+i}/{len(DATA_ITEM_CODES)}] ({pct:.1f}%) "
            f"{code} ... ",
            end="", flush=True,
        )

        success = False
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                definition = fetch_definition(driver, code)
                if definition:
                    definitions[code] = definition
                    save_progress(definitions)
                    print(f"OK ({len(definition)} chars)")
                    success = True
                    break
                else:
                    print(f"empty (attempt {attempt}/{MAX_RETRIES})", end=" ", flush=True)
            except Exception as e:
                err_msg = str(e).split("\n")[0][:80]
                print(f"error: {err_msg} (attempt {attempt}/{MAX_RETRIES})", end=" ", flush=True)
                # Try to re-navigate into the iframe in case we got kicked out
                try:
                    navigate_to_dib_frame(driver)
                except Exception:
                    pass
            time.sleep(1)

        if not success:
            print("FAILED")
            failed[code] = "No definition found"
            definitions[code] = None
            save_progress(definitions)

        time.sleep(PAUSE_BETWEEN)

    # Save final output (clean, without None entries)
    clean_definitions = {k: v for k, v in definitions.items() if v is not None}
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(clean_definitions, f, indent=2, ensure_ascii=False)

    print()
    print("=" * 60)
    print(f"Done! {len(clean_definitions)} definitions saved to {OUTPUT_FILE}")
    if failed:
        print(f"{len(failed)} codes had no definition found:")
        for code in failed:
            print(f"  - {code}")
    print("=" * 60)


if __name__ == "__main__":
    main()
